name: JE

on:
 push:
  branches:
   - '**'

# trigger workflow on file change
#on:
# push:
#  paths:
#   - 'version.txt'

# if: ${{ false }}

jobs:

# linux gcc ------------------------------------------------------------
 jelinux-gcc:
  name: JE (Linux gcc)
  runs-on: ubuntu-20.04
  steps:
   - name: Checkout Git repository
     uses: actions/checkout@v2

   - name: Setup Environment (Linux)
     run: script/install-lnx.sh

   - name: Build JE (Linux)
     env:
      CC: gcc
      USE_SLEEF: 1
     run: |
      script/buildga.sh linux
      script/testga.sh linux
      cd j64
      cd ..
      ls -l j64
      zip -r l64.zip j64

   - name: Release JE (Linux)
     uses: ncipollo/release-action@v1
     with:
      tag: build
      artifacts: "l64.zip"
      token: ${{ secrets.GITHUB_TOKEN }}
      allowUpdates: true
      replacesArtifacts: true

   - name: Copy Test (Linux)
     uses: actions/upload-artifact@v2
     with:
       name: dist
       path: testlinux.txt


# get tests ------------------------------------------------------------
 tests:
  name: Test Results
  runs-on: ubuntu-20.04
  needs: [jelinux-gcc]
  steps:
   - name: Checkout Git repository
     uses: actions/checkout@v2

   - name: Get Test Results
     uses: actions/download-artifact@v2
     with:
      name: dist

   - name: Merge Test Results
     run: script/testgares.sh

   - name: Copy Tests to Build
     uses: ncipollo/release-action@v1
     with:
      tag: build
      artifacts: "tests.txt"
      token: ${{ secrets.GITHUB_TOKEN }}
      allowUpdates: true
      replacesArtifacts: true

 webhook:
  name: Run Webhook
  runs-on: ubuntu-22.04
  needs: tests
  steps:
   - name: update server
     uses: distributhor/workflow-webhook@v2
     env:
      webhook_url: ${{ secrets.WEBHOOK_URL }}
      webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
      data: '{ "id": "jebuild" }'
